pipeline {
    agent any
    
    parameters {
        password(name: 'GITLAB_TOKEN', defaultValue: '', description: 'Enter GITLAB_TOKEN',)
        password(name: 'GITHUB_TOKEN', defaultValue: '', description: 'Enter GITHUB_TOKEN')
        string(name: 'GITLAB_LOG_PROJECT_PATH', defaultValue: '', description: 'Kindly paste in below format: \ngitlab_namespace/project_name')
    }
    
    
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/vinayhegde105/SCM-Migration-DEMO.git'
            }
        }
        
        stage('SCM Migration') {
            steps {
                script {
                    def gitlab_token = env.GITLAB_TOKEN
                    def github_token = env.GITHUB_TOKEN

                    sh '''
                        #!/bin/bash
                        export gitlab_token=$GITLAB_TOKEN
                        export github_token=$GITHUB_TOKEN
                        export repo_path=$GITLAB_LOG_PROJECT_PATH
                        # python3 gitlab-github/gitlab-github.py
                    '''
                    }
                }
            }
        }
    }
