pipeline {
    agent any
    
    parameters {
        password(name: 'GITLAB_TOKEN', defaultValue: '', description: 'Enter GITLAB_TOKEN',)
        password(name: 'AZURE_TOKEN', defaultValue: '', description: 'Enter AZURE_TOKEN')
        string(name: 'GITLAB_LOG_PROJECT_PATH', defaultValue: '', description: 'Kindly paste in below format: \ngitlab_namespace/project_name')
    }
    
    
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/vinayhegde105/SCM-Migration-DEMO.git'
            }
        }
        
        stage('SCM Migration') {
            steps {
                script {
        wrap([$class: 'MaskPasswordsBuildWrapper',
              varPasswordPairs: [
                  [password: "${GITLAB_TOKEN}", var: 'USR'],
                  [password: "${AZURE_TOKEN}", var: 'PSW']
              ]
        ]) {
            sh '''
                #!/bin/bash
                export gitlab_token=$GITLAB_TOKEN
                export azure_token=$AZURE_TOKEN
                export repo_path=$GITLAB_LOG_PROJECT_PATH
            '''
        }
    }
            }
        }
    }
