pipeline {
    agent any
    
    parameters {
        password(name: 'GITHUB_TOKEN', defaultValue: '', description: 'Enter GITHUB_TOKEN')
        password(name: 'GITLAB_TOKEN', defaultValue: '', description: 'Enter GITLAB_TOKEN',)
        string(name: 'GITLAB_LOG_PROJECT_PATH', defaultValue: '', description: 'Kindly paste in below format: \ngitlab_namespace/project_name')
    }
    
    
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/vinayhegde105/SCM-Migration-DEMO.git'
            }
        }
        
        stage('SCM Migration') {
            steps {
                script {
        wrap([$class: 'MaskPasswordsBuildWrapper',
              varPasswordPairs: [
                  [password: "${GITHUB_TOKEN}", var: 'GITHUB_TOKEN'],
                  [password: "${GITLAB_TOKEN}", var: 'GITLAB_TOKEN']
              ]
        ]) {
            sh '''
                #!/bin/bash
                export gitlab_token=$GITLAB_TOKEN
                export github_token=$GITHUB_TOKEN
                export repo_path=$GITLAB_LOG_PROJECT_PATH
                python3 github-gitlab/github-gitlab.py
            '''
        }
    }
            }
        }
    }
}
