pipeline {
    agent any
    
    parameters {
        string(name: 'BITBUCKET_USERNAME', defaultValue: '', description: 'Enter BITBUCKET_USERNAME')
        password(name: 'BITBUCKET_PASSWORD', defaultValue: '', description: 'Enter BITBUCKET_PASSWORD')
        password(name: 'GITHUB_TOKEN', defaultValue: '', description: 'Enter GITHUB_TOKEN')
        password(name: 'GITLAB_TOKEN', defaultValue: '', description: 'Enter GITLAB_TOKEN')
        string(name: 'GITLAB_LOG_PROJECT_PATH', defaultValue: '', description: 'Kindly paste in below format: \ngitlab_namespace/project_name')
    }
    
    
    stages {
        stage('Clone Repository') {
            steps {
                git credentialsId: 'SCM_MIGRATOR_CRED', branch: 'main', url: '${SCM_MIGRATOR_SOURCE_CODE}'
            }
        }
        
        stage('SCM Migration') {
            steps {
                script {
        wrap([$class: 'MaskPasswordsBuildWrapper',
              varPasswordPairs: [
                  [password: "${BITBUCKET_PASSWORD}", var: 'BITBUCKET_PASSWORD'],
                  [password: "${GITHUB_TOKEN}", var: 'GITHUB_TOKEN'],
                  [password: "${GITLAB_TOKEN}", var: 'GITLAB_TOKEN']
              ]
        ]) {
            sh '''
                #!/bin/bash
                export bitbucket_username=$BITBUCKET_USERNAME
                export bitbucket_password=$BITBUCKET_PASSWORD
                export github_token=$GITHUB_TOKEN
                export gitlab_token=$GITLAB_TOKEN
                export repo_path=$GITLAB_LOG_PROJECT_PATH
                pip3 install pandas
                pip3 install openpyxl
                python3 github-bitbucket/github-bitbucket.py
            '''
        }
    }
            }
        }
        // stage('Send Email') {
        //     steps {
        //         script {
        //             emailext attachmentsPattern: '*.csv', 
        //                         body: 'Please find the attached CSV files.', 
        //                         mimeType: 'text/csv', 
        //                         subject: 'CSV Files',
        //                         to: 'sssssabhahit@gmail.com'
        //             }
        //     }
        // }
    }
}